--- #YAML:1.0
name:                HTTP-Response-Encoding
version:             0.05
abstract:            Adds encoding() to HTTP::Response
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Encode:                        2
    HTTP::Response:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Dan Kogai <dankogai@dan.co.jp>
